# Temporary workaround for issue with rubygems 2.2.0 with bundler 1.5 on ruby
# 1.8.7.
#
# A fix has been merged to rubygems but not yet released. See:
# https://github.com/rubygems/rubygems/commit/f8e0f1d5f67cfc4e1966cc1e2db367aebf8a09e4
#
# See also CHEF-4916
#
# This workaround should be removed when that fix is released.
before_install:
  - gem update --system 2.1.11
  - gem --version

matrix:
  include:
    # Commenting these out for now so that Travis runs don't take forever to
    # get to the parts I'm working on right now...
    # - rvm: 1.8.7-p374
    # - rvm: 1.9.3
    # - rvm: 2.0.0
    # - rvm: 2.1.1
    # - rvm: 2.1.1
    #   gemfile: pedant.gemfile
    #   script: bundle exec rake pedant
    - rvm: 2.1.1
      gemfile: spec/e2e/Gemfile
      before_script: cd spec/e2e
      script: bundle exec kitchen test default-ubuntu-1204 -l debug
      env:
        # access key id
        - secure: "cSoSxpNYaAjZRn5vbvPrSGZJ3qnQSD3gBriErMO8Y53wFfswViqSbrc57TYR8tROHcbhi0Sj5ar7p9nyKZNj5Wr+UIkd4jRthbpS9GBVAVscmTOotgbZt1o1QeJ0ZarE3JzrpTQPnDM++QtVOD8+WOp2VvSIGN24fhuvV5jKtzk="
        # secret access key
        - secure: "M/NeE28egHUKFLfToMKuVVvQuGbBGz4k6xlYV37vACk7d88qqREXWh6dS0xJY8zptJkc1QHS6Xzb3uqT1vYr65JJ7v0zjhLxaqeTzaq5FfPJoFVkMatRDtFydIP/7iPz/FADoC8HeFb5O2S6YvlO7CUHsVx2qEtwTZC31azPg/Q="
        # ssh key id
        - secure: "Kx+2+duNRhSaYj1MoBqM0kgP5y2gUyQq17x6uqAh2gpWiU7DpkHm5R40Llk6TQjHpkzwe5JGWcnMzhQV61F7r4fKPS53qbRW2nFJogCt/nZDKRIY6oV4a3Cgyw6XVuZuRN/VF/UP/cew3mVzhq27ic3YMZl9CPUBtL5i2268bHU="
        # iam profile name
        - secure: "RYrepkubeOJs5BmH296X/BIkyKSOIL7Exmnhp14LouOgkbuHGgMnMqLF5UlOL0st3Fg4F3/ywbZTrbX9shkNH6SVoGFBwGXgMeMKbdxHDa4y3oXAgJUV92lOiOima8/Ws8dnyr1hZeVxb421ajnX+pAC/pNA0jkprDGUHzulttE="

branches:
  only:
    - master
    - 10-stable
    - 11-stable

script: bundle exec rspec --color --format progress

notifications:
  on_success: change
  on_failure: always
  on_start: false
  irc:
    channels:
      - "chat.freenode.net#chef-hacking"
  webhooks:
    urls:
      # Gitter IM
      - secure: "HmMKr/ysKVyKUJ24PRCHcA8QCmlFoukrYumY0GRLzvaFWO8PknHO1t/0RbrKRb2ed/hgkFd+RKNCYvSvcE8Ahr2vlMrBeGHGfVeOGkWtbhLgNqo1b50Ll9CqvTM8X2ZIq6hIWraanwoYRQu/8uGL29yH4lBi7DhpTkFwBMLulhQ="
  hipchat:
    rooms:
      # Build Statuses
      - secure: "G8MNo94L8bmWWwkH2/ViB2QaZnZHZscYM/mEjDbOGd15sqrruwckeARyBoUcRI7P1C6AFmS4IKCNVXa6KzX4Pbh51gQWM92zRpRTZpplwtXz53/1l8ajLFLLMLvEMTlBFAANUKEUFAQPY4dMa14V3Qc5oijfIncN61k4nZNTKpY="
      # Open Source
      - secure: "hmcex4PpG5dn8WvjndONO4xCUKOC5kPU/bUEGRrfVbe2YKJE7t0XXbNDC96W/xBgzgnJzvf1Er0zJKDrNf4qEDEWFoozdN00WLcqREgaLLS3Seto2FjR/BpBk5q+sCV0rwwEMms2P4Qk+VSnDCnm9EaeM55hOabqNuOrRzoZLBQ="
